#cloud-config
#
#  Set machine default values
#
users:
  - default
  - name: ansible
    gecos: Ansible
    shell: /bin/bash
    groups: sudo
    ssh_import_id: None
    lock_passwd: True
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCNaVP0USq5F3TYVQ6JKdwJzrbXwgg2Wvod2nKDM+T0dBsiI0jjrFEnYQoyawyUt8yQgQ2gx2PBnbwP/UTnpT1LKiwKG1Lqc3N5WAqJTf3Ih+H9i5QWL/9Nzjcnl6zT6LklegqOtv8pHzBcwpTUXKiwXO0Q3K38hgLJq4LVvrfpONalwTipWFak1h001VW3y/FCio7JWbuD7XCE5NSxSBRbzzIYvxm6cukbn4b3e1/lDH66IgliopPg9v0yS1nJmtUWUWPdXzmvJmPDOYDBm7o5vbyhQkcGJA9sf/PD+nrkUduD0UY9HaCImj+waIdD6S8h4CWnNzrrq3OuKvvGVSN9tU2mmeBCPPq8sYc3V8V8uz5MXvT/w/FtChby5Fg5rES/k1sRkMhb7LHRe/p8HBBI2EDanfUIxv8yVZ00JegoGlvbVCffbFl2rTdcl7eyKMDlaiVjC9sH1pAXRcZuA7psVao5TKIHYc6ohzUgZ7m7jfmEV1BZHBW6MDkXeMSh2v94vCKkzC+LQmwzoxnW0CnmUvEQ/CvOe0oxiVOJpM4I12gKB/VhIJ/uHBrZJ4taywcx54hrZCDYXhy2FH4wxQHbG7BclXE2tv1ceOtoGCqsQTXTcObjDOx6JXfuP45piNY85USIDSKKufmCTi1rb1YVbqZQqOXXtjLq0Yo2XEbiQ== ansible@local

write_files:
  - path: /etc/sudoers.d/90-ansible
    permissions: '0440'
    owner: root:root
    content: |
      #  Disable tty to enable Ansible pipelining
      Defaults:ansible !requiretty
      ansible ALL=(ALL) NOPASSWD:ALL
  - path: /var/lib/cloud/instance/warnings/.skip
    permissions: '0644'
    owner: root:root

power_state:
  delay: "+1"
  mode: reboot
  message: Bye Bye
  timeout: 120
  condition: True
